Vagrant.configure("2") do |config|
  
    # Definindo a imagem da box que será usada
    config.vm.box = "generic/centos8"
    
    # Configurando a rede privada da VM
    config.vm.network "private_network", ip: "192.168.33.20"
    
    # Configurando os recursos da VM (memória e CPU)
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    
    # Provisionando a VM com um script shell
    config.vm.provision "shell", path: "provision-centos.sh"
  end